name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: rojopolis/spellcheck-github-actions@0.36.0
      name: Spellcheck
      with:
        config_path: .github/spellcheck.toml
